# Case Study Credit Card
Let's proceed with hierarchical clustering using the "Credit Card" dataset. We will demonstrate the agglomerative hierarchical clustering method, which is a popular hierarchical clustering approach.

## Setup
Dataset Loading and Exploration

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage

## Load Dataset

In [2]:
df = pd.read_csv("Credit_Card_Dataset_for_Clustering.csv", delimiter=',')
nRow, nCol = df.shape

print(f'There are {nRow} rows and {nCol} columns')

There are 8950 rows and 18 columns

## Exploratory Analysis

In [3]:
df.head()

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
0,C10001,40.900749,0.818182,95.40,0.00,95.4,0.000000,0.166667,0.000000,0.083333,0.000000,0,2,1000.0,201.802084,139.509787,0.000000,12
1,C10002,3202.467416,0.909091,0.00,0.00,0.0,6442.945483,0.000000,0.000000,0.000000,0.250000,4,0,7000.0,4103.032597,1072.340217,0.222222,12
2,C10003,2495.148862,1.000000,773.17,773.17,0.0,0.000000,1.000000,1.000000,0.000000,0.000000,0,12,7500.0,622.066742,627.284787,0.000000,12
3,C10004,1666.670542,0.636364,1499.00,1499.00,0.0,205.788017,0.083333,0.083333,0.000000,0.083333,1,1,7500.0,0.000000,NaN,0.000000,12
4,C10005,817.714335,1.000000,16.00,16.00,0.0,0.000000,0.083333,0.083333,0.000000,0.000000,0,1,1200.0,678.334763,244.791237,0.000000,12

In [4]:
df.tail()

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
8945,C19186,28.493517,1.000000,291.12,0.00,291.12,0.000000,1.000000,0.000000,0.833333,0.000000,0,6,1000.0,325.594462,48.886365,0.50,6
8946,C19187,19.183215,1.000000,300.00,0.00,300.00,0.000000,1.000000,0.000000,0.833333,0.000000,0,6,1000.0,275.861322,NaN,0.00,6
8947,C19188,23.398673,0.833333,144.40,0.00,144.40,0.000000,0.833333,0.000000,0.666667,0.000000,0,5,1000.0,81.270775,82.418369,0.25,6
8948,C19189,13.457564,0.833333,0.00,0.00,0.00,36.558778,0.000000,0.000000,0.000000,0.166667,2,0,500.0,52.549959,55.755628,0.25,6
8949,C19190,372.708075,0.666667,1093.25,1093.25,0.00,127.040008,0.666667,0.666667,0.000000,0.333333,2,23,1200.0,63.165404,88.288956,0.00,6

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8950 entries, 0 to 8949
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   CUST_ID                           8950 non-null   object
 1   BALANCE                           8950 non-null   float64
 2   BALANCE_FREQUENCY                 8950 non-null   float64
 3   PURCHASES                         8950 non-null   float64
 4   ONEOFF_PURCHASES                  8950 non-null   float64
 5   INSTALLMENTS_PURCHASES            8950 non-null   float64
 6   CASH_ADVANCE                      8950 non-null   float64
 7   PURCHASES_FREQUENCY               8950 non-null   float64
 8   ONEOFF_PURCHASES_FREQUENCY        8950 non-null   float64
 9   PURCHASES_INSTALLMENTS_FREQUENCY  8950 non-null   float64
 10  CASH_ADVANCE_FREQUENCY            8950 non-null   float64
 11  CASH_ADVANCE_TRX                  8950 non-null   int64
 12  PURCHASES_TRX                     8950 non-null   int64
 13  CREDIT_LIMIT                      8949 non-null   float64
 14  PAYMENTS                          8950 non-null   float64
 15  MINIMUM_PAYMENTS                  8637 non-null   float64
 16  PRC_FULL_PAYMENT                  8950 non-null   float64
 17  TENURE                            8950 non-null   int64
dtypes: float64(14), int64(3), object(1)
memory usage: 1.2+ MB
None

In [6]:
print(df.describe())

            BALANCE  BALANCE_FREQUENCY     PURCHASES  ONEOFF_PURCHASES  \
count   8950.000000        8950.000000   8950.000000       8950.000000
mean    1564.474828           0.877271   1003.204834        592.437371
std     2081.531879           0.236904   2136.634782       1659.887917
min        0.000000           0.000000      0.000000          0.000000
25%      128.281915           0.888889     39.635000          0.000000
50%      873.385231           1.000000    361.280000         38.000000
75%     2054.140036           1.000000   1110.130000        577.405000
max    19043.138560           1.000000  49039.570000      40761.250000

       INSTALLMENTS_PURCHASES  CASH_ADVANCE  PURCHASES_FREQUENCY  \
count             8950.000000   8950.000000          8950.000000
mean               411.067645    978.871112             0.490351
std                904.338115   2097.163877             0.401371
min                  0.000000      0.000000             0.000000
25%                  0.000000      0.000000             0.083333
50%                 89.000000      0.000000             0.500000
75%                468.637500   1113.821139             0.916667
max              22500.000000  47137.211760             1.000000

       ONEOFF_PURCHASES_FREQUENCY  PURCHASES_INSTALLMENTS_FREQUENCY  \
count                 8950.000000                       8950.000000
mean                     0.202458                          0.364437
std                      0.298336                          0.397448
min                      0.000000                          0.000000
25%                      0.000000                          0.000000
50%                      0.083333                          0.166667
75%                      0.300000                          0.750000
max                      1.000000                          1.000000

       CASH_ADVANCE_FREQUENCY  CASH_ADVANCE_TRX  PURCHASES_TRX  CREDIT_LIMIT  \
count             8950.000000       8950.000000    8950.000000   8949.000000
mean                 0.135144          3.248827      14.709832   4494.449450
std                  0.200121          6.824647      24.857649   3638.815725
min                  0.000000          0.000000       0.000000     50.000000
25%                  0.000000          0.000000       1.000000   1600.000000
50%                  0.000000          0.000000       7.000000   3000.000000
75%                  0.222222          4.000000      17.000000   6500.000000
max                  1.500000        123.000000     358.000000  30000.000000

           PAYMENTS  MINIMUM_PAYMENTS  PRC_FULL_PAYMENT       TENURE
count   8950.000000       8637.000000       8950.000000  8950.000000
mean    1733.143852        864.206542          0.153715    11.517318
std     2895.063757       2372.446607          0.292499     1.338331
min        0.000000          0.019163          0.000000     6.000000
25%      383.276166        169.123707          0.000000    12.000000
50%      856.901546        312.343947          0.000000    12.000000
75%     1901.134317        825.485459          0.142857    12.000000
max    50721.483360      76406.207520          1.000000    12.000000

In [7]:
print(df.describe(include='all'))

       CUST_ID       BALANCE  BALANCE_FREQUENCY     PURCHASES  \
count     8950   8950.000000        8950.000000   8950.000000
unique    8950           NaN                NaN           NaN
top     C10001           NaN                NaN           NaN
freq         1           NaN                NaN           NaN
mean       NaN   1564.474828           0.877271   1003.204834
std        NaN   2081.531879           0.236904   2136.634782
min        NaN      0.000000           0.000000      0.000000
25%        NaN    128.281915           0.888889     39.635000
50%        NaN    873.385231           1.000000    361.280000
75%        NaN   2054.140036           1.000000   1110.130000
max        NaN  19043.138560           1.000000  49039.570000

        ONEOFF_PURCHASES  INSTALLMENTS_PURCHASES  CASH_ADVANCE  \
count        8950.000000             8950.000000   8950.000000
unique               NaN                     NaN           NaN
top                  NaN                     NaN           NaN
freq                 NaN                     NaN           NaN
mean          592.437371              411.067645    978.871112
std          1659.887917              904.338115   2097.163877
min             0.000000                0.000000      0.000000
25%             0.000000                0.000000      0.000000
50%            38.000000               89.000000      0.000000
75%           577.405000              468.637500   1113.821139
max         40761.250000            22500.000000  47137.211760

        PURCHASES_FREQUENCY  ONEOFF_PURCHASES_FREQUENCY  \
count           8950.000000                 8950.000000
unique                  NaN                         NaN
top                     NaN                         NaN
freq                    NaN                         NaN
mean               0.490351                    0.202458
std                0.401371                    0.298336
min                0.000000                    0.000000
25%                0.083333                    0.000000
50%                0.500000                    0.083333
75%                0.916667                    0.300000
max                1.000000                    1.000000

        PURCHASES_INSTALLMENTS_FREQUENCY  CASH_ADVANCE_FREQUENCY  \
count                        8950.000000             8950.000000
unique                               NaN                     NaN
top                                  NaN                     NaN
freq                                 NaN                     NaN
mean                            0.364437                0.135144
std                             0.397448                0.200121
min                             0.000000                0.000000
25%                             0.000000                0.000000
50%                             0.166667                0.000000
75%                             0.750000                0.222222
max                             1.000000                1.500000

        CASH_ADVANCE_TRX  PURCHASES_TRX  CREDIT_LIMIT      PAYMENTS  \
count        8950.000000    8950.000000   8949.000000   8950.000000
unique               NaN            NaN           NaN           NaN
top                  NaN            NaN           NaN           NaN
freq                 NaN            NaN           NaN           NaN
mean            3.248827      14.709832   4494.449450   1733.143852
std             6.824647      24.857649   3638.815725   2895.063757
min             0.000000       0.000000     50.000000      0.000000
25%             0.000000       1.000000   1600.000000    383.276166
50%             0.000000       7.000000   3000.000000    856.901546
75%             4.000000      17.000000   6500.000000   1901.134317
max           123.000000     358.000000  30000.000000  50721.483360

        MINIMUM_PAYMENTS  PRC_FULL_PAYMENT       TENURE
count        8637.000000       8950.000000  8950.000000
unique               NaN               NaN          NaN
top                  NaN               NaN          NaN
freq                 NaN               NaN          NaN
mean          864.206542          0.153715    11.517318
std          2372.446607          0.292499     1.338331
min             0.019163          0.000000     6.000000
25%           169.123707          0.000000    12.000000
50%           312.343947          0.000000    12.000000
75%           825.485459          0.142857    12.000000
max         76406.207520          1.000000    12.000000

## Cleanup NaNs

In [8]:
df = df.dropna()

## Split Features and Target

### Features

Try with less features than the full dataset

In [9]:
X = df.iloc[:, 1:4]
X.head()

       BALANCE  BALANCE_FREQUENCY  PURCHASES
0    40.900749           0.818182      95.40
1  3202.467416           0.909091       0.00
2  2495.148862           1.000000     773.17
4   817.714335           1.000000      16.00
5  1809.828751           1.000000    1333.28

## Data Preprocessing
Before applying hierarchical clustering, we need to preprocess the data to standardize the features.

In [10]:
# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

## Agglomerative Hierarchical Clustering

In [11]:
# Initialize the Agglomerative clustering algorithm with a specific number of clusters (n_clusters)
agglomerative = AgglomerativeClustering(n_clusters=3)

# Fit the model to the data
agglomerative.fit(X_scaled)

# Get the cluster assignments for each sample
agglomerative_labels = agglomerative.labels_

print(f"Agglomerative Hierarchical Clustering:")
print(f"Cluster Assignments: {agglomerative_labels}")

Agglomerative Hierarchical Clustering:
Cluster Assignments: [2 0 2 ... 2 2 1]